# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/icnet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.pspnet_pb2
import protos.hyperparams_pb2
import protos.losses_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/icnet.proto',
  package='fast_semantic_segmentation.protos',
  serialized_pb=_b('\n\x12protos/icnet.proto\x12!fast_semantic_segmentation.protos\x1a\x13protos/pspnet.proto\x1a\x18protos/hyperparams.proto\x1a\x13protos/losses.proto\"\xe1\x03\n\x05ICNet\x12\x13\n\x0bnum_classes\x18\x01 \x01(\x05\x12Y\n\x11\x66\x65\x61ture_extractor\x18\x02 \x01(\x0b\x32>.fast_semantic_segmentation.protos.PSPNetICNetFeatureExtractor\x12\x43\n\x0bhyperparams\x18\x03 \x01(\x0b\x32..fast_semantic_segmentation.protos.Hyperparams\x12\x35\n\x04loss\x18\x04 \x01(\x0b\x32\'.fast_semantic_segmentation.protos.Loss\x12\"\n\x17main_branch_loss_weight\x18\x05 \x01(\x02:\x01\x31\x12&\n\x19second_branch_loss_weight\x18\x06 \x01(\x02:\x03\x30.4\x12%\n\x18\x66irst_branch_loss_weight\x18\x07 \x01(\x02:\x03\x30.4\x12\x14\n\x0c\x66ilter_scale\x18\x08 \x01(\x02\x12\x17\n\x0fpooling_factors\x18\t \x03(\x02\x12*\n\x1bpretrain_single_branch_mode\x18\n \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x0fmobile_ops_only\x18\x0b \x01(\x08:\x05\x66\x61lse')
  ,
  dependencies=[protos.pspnet_pb2.DESCRIPTOR,protos.hyperparams_pb2.DESCRIPTOR,protos.losses_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ICNET = _descriptor.Descriptor(
  name='ICNet',
  full_name='fast_semantic_segmentation.protos.ICNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='fast_semantic_segmentation.protos.ICNet.num_classes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='fast_semantic_segmentation.protos.ICNet.feature_extractor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hyperparams', full_name='fast_semantic_segmentation.protos.ICNet.hyperparams', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss', full_name='fast_semantic_segmentation.protos.ICNet.loss', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_branch_loss_weight', full_name='fast_semantic_segmentation.protos.ICNet.main_branch_loss_weight', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second_branch_loss_weight', full_name='fast_semantic_segmentation.protos.ICNet.second_branch_loss_weight', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_branch_loss_weight', full_name='fast_semantic_segmentation.protos.ICNet.first_branch_loss_weight', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_scale', full_name='fast_semantic_segmentation.protos.ICNet.filter_scale', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pooling_factors', full_name='fast_semantic_segmentation.protos.ICNet.pooling_factors', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pretrain_single_branch_mode', full_name='fast_semantic_segmentation.protos.ICNet.pretrain_single_branch_mode', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobile_ops_only', full_name='fast_semantic_segmentation.protos.ICNet.mobile_ops_only', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=607,
)

_ICNET.fields_by_name['feature_extractor'].message_type = protos.pspnet_pb2._PSPNETICNETFEATUREEXTRACTOR
_ICNET.fields_by_name['hyperparams'].message_type = protos.hyperparams_pb2._HYPERPARAMS
_ICNET.fields_by_name['loss'].message_type = protos.losses_pb2._LOSS
DESCRIPTOR.message_types_by_name['ICNet'] = _ICNET

ICNet = _reflection.GeneratedProtocolMessageType('ICNet', (_message.Message,), dict(
  DESCRIPTOR = _ICNET,
  __module__ = 'protos.icnet_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.ICNet)
  ))
_sym_db.RegisterMessage(ICNet)


# @@protoc_insertion_point(module_scope)
