# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/input_reader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/input_reader.proto',
  package='fast_semantic_segmentation.protos',
  serialized_pb=_b('\n\x19protos/input_reader.proto\x12!fast_semantic_segmentation.protos\"\xbd\x02\n\x0bInputReader\x12\x15\n\x07shuffle\x18\x01 \x01(\x08:\x04true\x12\x1c\n\x0equeue_capacity\x18\x02 \x01(\r:\x04\x32\x30\x30\x30\x12\x1f\n\x11min_after_dequeue\x18\x03 \x01(\r:\x04\x31\x30\x30\x30\x12\x15\n\nnum_epochs\x18\x04 \x01(\r:\x01\x30\x12\x16\n\x0bnum_readers\x18\x05 \x01(\r:\x01\x31\x12\x1d\n\x12num_parallel_calls\x18\x06 \x01(\r:\x01\x31\x12\x1c\n\x0eshuffle_buffer\x18\x07 \x01(\r:\x04\x32\x30\x34\x38\x12V\n\x16tf_record_input_reader\x18\x08 \x01(\x0b\x32\x36.fast_semantic_segmentation.protos.TFRecordInputReader\x12\x14\n\x0cnum_examples\x18\t \x01(\r\")\n\x13TFRecordInputReader\x12\x12\n\ninput_path\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INPUTREADER = _descriptor.Descriptor(
  name='InputReader',
  full_name='fast_semantic_segmentation.protos.InputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shuffle', full_name='fast_semantic_segmentation.protos.InputReader.shuffle', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queue_capacity', full_name='fast_semantic_segmentation.protos.InputReader.queue_capacity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_after_dequeue', full_name='fast_semantic_segmentation.protos.InputReader.min_after_dequeue', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_epochs', full_name='fast_semantic_segmentation.protos.InputReader.num_epochs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_readers', full_name='fast_semantic_segmentation.protos.InputReader.num_readers', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_parallel_calls', full_name='fast_semantic_segmentation.protos.InputReader.num_parallel_calls', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shuffle_buffer', full_name='fast_semantic_segmentation.protos.InputReader.shuffle_buffer', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2048,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tf_record_input_reader', full_name='fast_semantic_segmentation.protos.InputReader.tf_record_input_reader', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_examples', full_name='fast_semantic_segmentation.protos.InputReader.num_examples', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=382,
)


_TFRECORDINPUTREADER = _descriptor.Descriptor(
  name='TFRecordInputReader',
  full_name='fast_semantic_segmentation.protos.TFRecordInputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_path', full_name='fast_semantic_segmentation.protos.TFRecordInputReader.input_path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=425,
)

_INPUTREADER.fields_by_name['tf_record_input_reader'].message_type = _TFRECORDINPUTREADER
DESCRIPTOR.message_types_by_name['InputReader'] = _INPUTREADER
DESCRIPTOR.message_types_by_name['TFRecordInputReader'] = _TFRECORDINPUTREADER

InputReader = _reflection.GeneratedProtocolMessageType('InputReader', (_message.Message,), dict(
  DESCRIPTOR = _INPUTREADER,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.InputReader)
  ))
_sym_db.RegisterMessage(InputReader)

TFRecordInputReader = _reflection.GeneratedProtocolMessageType('TFRecordInputReader', (_message.Message,), dict(
  DESCRIPTOR = _TFRECORDINPUTREADER,
  __module__ = 'protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.TFRecordInputReader)
  ))
_sym_db.RegisterMessage(TFRecordInputReader)


# @@protoc_insertion_point(module_scope)
