# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.eval_pb2
import protos.input_reader_pb2
import protos.model_pb2
import protos.train_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pipeline.proto',
  package='fast_semantic_segmentation.protos',
  serialized_pb=_b('\n\x15protos/pipeline.proto\x12!fast_semantic_segmentation.protos\x1a\x11protos/eval.proto\x1a\x19protos/input_reader.proto\x1a\x12protos/model.proto\x1a\x12protos/train.proto\"\xfa\x02\n\x0ePipelineConfig\x12G\n\x05model\x18\x01 \x01(\x0b\x32\x38.fast_semantic_segmentation.protos.FastSegmentationModel\x12\x44\n\x0ctrain_config\x18\x02 \x01(\x0b\x32..fast_semantic_segmentation.protos.TrainConfig\x12J\n\x12train_input_reader\x18\x03 \x01(\x0b\x32..fast_semantic_segmentation.protos.InputReader\x12\x42\n\x0b\x65val_config\x18\x04 \x01(\x0b\x32-.fast_semantic_segmentation.protos.EvalConfig\x12I\n\x11\x65val_input_reader\x18\x05 \x01(\x0b\x32..fast_semantic_segmentation.protos.InputReader')
  ,
  dependencies=[protos.eval_pb2.DESCRIPTOR,protos.input_reader_pb2.DESCRIPTOR,protos.model_pb2.DESCRIPTOR,protos.train_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIPELINECONFIG = _descriptor.Descriptor(
  name='PipelineConfig',
  full_name='fast_semantic_segmentation.protos.PipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='fast_semantic_segmentation.protos.PipelineConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='fast_semantic_segmentation.protos.PipelineConfig.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_input_reader', full_name='fast_semantic_segmentation.protos.PipelineConfig.train_input_reader', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='fast_semantic_segmentation.protos.PipelineConfig.eval_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_input_reader', full_name='fast_semantic_segmentation.protos.PipelineConfig.eval_input_reader', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=525,
)

_PIPELINECONFIG.fields_by_name['model'].message_type = protos.model_pb2._FASTSEGMENTATIONMODEL
_PIPELINECONFIG.fields_by_name['train_config'].message_type = protos.train_pb2._TRAINCONFIG
_PIPELINECONFIG.fields_by_name['train_input_reader'].message_type = protos.input_reader_pb2._INPUTREADER
_PIPELINECONFIG.fields_by_name['eval_config'].message_type = protos.eval_pb2._EVALCONFIG
_PIPELINECONFIG.fields_by_name['eval_input_reader'].message_type = protos.input_reader_pb2._INPUTREADER
DESCRIPTOR.message_types_by_name['PipelineConfig'] = _PIPELINECONFIG

PipelineConfig = _reflection.GeneratedProtocolMessageType('PipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINECONFIG,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.PipelineConfig)
  ))
_sym_db.RegisterMessage(PipelineConfig)


# @@protoc_insertion_point(module_scope)
