# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pspnet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.hyperparams_pb2
import protos.losses_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pspnet.proto',
  package='fast_semantic_segmentation.protos',
  serialized_pb=_b('\n\x13protos/pspnet.proto\x12!fast_semantic_segmentation.protos\x1a\x18protos/hyperparams.proto\x1a\x13protos/losses.proto\"\xa3\x02\n\x06PSPNet\x12\x13\n\x0bnum_classes\x18\x01 \x01(\x05\x12Y\n\x11\x66\x65\x61ture_extractor\x18\x02 \x01(\x0b\x32>.fast_semantic_segmentation.protos.PSPNetICNetFeatureExtractor\x12\x43\n\x0bhyperparams\x18\x03 \x01(\x0b\x32..fast_semantic_segmentation.protos.Hyperparams\x12\x35\n\x04loss\x18\x04 \x01(\x0b\x32\'.fast_semantic_segmentation.protos.Loss\x12\x14\n\x0c\x66ilter_scale\x18\x05 \x01(\x02\x12\x17\n\x0fpooling_factors\x18\x06 \x03(\x02\"+\n\x1bPSPNetICNetFeatureExtractor\x12\x0c\n\x04type\x18\x01 \x01(\t')
  ,
  dependencies=[protos.hyperparams_pb2.DESCRIPTOR,protos.losses_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PSPNET = _descriptor.Descriptor(
  name='PSPNet',
  full_name='fast_semantic_segmentation.protos.PSPNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='fast_semantic_segmentation.protos.PSPNet.num_classes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='fast_semantic_segmentation.protos.PSPNet.feature_extractor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hyperparams', full_name='fast_semantic_segmentation.protos.PSPNet.hyperparams', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss', full_name='fast_semantic_segmentation.protos.PSPNet.loss', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_scale', full_name='fast_semantic_segmentation.protos.PSPNet.filter_scale', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pooling_factors', full_name='fast_semantic_segmentation.protos.PSPNet.pooling_factors', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=397,
)


_PSPNETICNETFEATUREEXTRACTOR = _descriptor.Descriptor(
  name='PSPNetICNetFeatureExtractor',
  full_name='fast_semantic_segmentation.protos.PSPNetICNetFeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='fast_semantic_segmentation.protos.PSPNetICNetFeatureExtractor.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=442,
)

_PSPNET.fields_by_name['feature_extractor'].message_type = _PSPNETICNETFEATUREEXTRACTOR
_PSPNET.fields_by_name['hyperparams'].message_type = protos.hyperparams_pb2._HYPERPARAMS
_PSPNET.fields_by_name['loss'].message_type = protos.losses_pb2._LOSS
DESCRIPTOR.message_types_by_name['PSPNet'] = _PSPNET
DESCRIPTOR.message_types_by_name['PSPNetICNetFeatureExtractor'] = _PSPNETICNETFEATUREEXTRACTOR

PSPNet = _reflection.GeneratedProtocolMessageType('PSPNet', (_message.Message,), dict(
  DESCRIPTOR = _PSPNET,
  __module__ = 'protos.pspnet_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.PSPNet)
  ))
_sym_db.RegisterMessage(PSPNet)

PSPNetICNetFeatureExtractor = _reflection.GeneratedProtocolMessageType('PSPNetICNetFeatureExtractor', (_message.Message,), dict(
  DESCRIPTOR = _PSPNETICNETFEATUREEXTRACTOR,
  __module__ = 'protos.pspnet_pb2'
  # @@protoc_insertion_point(class_scope:fast_semantic_segmentation.protos.PSPNetICNetFeatureExtractor)
  ))
_sym_db.RegisterMessage(PSPNetICNetFeatureExtractor)


# @@protoc_insertion_point(module_scope)
